name: e_presensi
description: Mobile Absensi SMAN 2 Tanggul
environment:
  sdk: ">=3.24.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.0
  camera: ^0.11.0
  geolocator: ^12.0.0
  http: ^1.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
